web:
  image: welance/craft
  ports:
    - 80:80
  volumes:
    - /var/log
    - ~/workspaces/project/config:/var/www/localhost/craft/config
    - ~/workspaces/project/templates:/var/www/localhost/craft/templates
    - ~/workspaces/project/plugins:/var/www/localhost/craft/plugins
    - ~/workspaces/project/public:/var/www/localhost/htdocs
  links:
    - database
  # env vars are replaced in /craft/config
  environment:
    # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
    LANG: C.UTF-8

    # DB is linked
    DB_HOST: database
    DB_NAME: craft
    DB_PORT: 3306
    DB_USER: craft
    DB_PASS: craft

database:
    image: mysql:5.5
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=craft
      - MYSQL_DATABASE=craft
      - MYSQL_USER=craft
      - MYSQL_PASSWORD=craft

redis:
  image: redis:3.2.8-alpine
  volumes:
    - /data:/data
